services:
  backend:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    env_file: .env
    restart: always
    depends_on:
      - edgedb
    volumes:
      - .:/code
    command: uvicorn app.main:app --port 8000 --host 0.0.0.0
    ports:
      - "8000:8000"
  edgedb:
    image: edgedb/edgedb
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
    volumes:
      - "./dbschema:/dbschema"
    ports:
      - "5656:5656"